-- hw_spam_rule 초기 데이터 - RuleBasedSpamChecker에 원래 내장돼 있던 기본 룰셋과 동일하다.
-- 표준 ANSI INSERT라 오라클/마리아DB/MSSQL 모두에서 그대로 쓸 수 있다. 테이블 생성
-- (각 dialect의 hw_spam_rule-schema.sql) 후 DBA가 1회성으로 적용한다. id는 자동 채번이므로
-- 컬럼 목록에서 제외한다.

INSERT INTO hw_spam_rule (rule_type, pattern, weight, enabled, reason, created_at) VALUES
  ('KEYWORD', 'viagra|cialis', 4.0, 1, '영문 고전 스팸(의약품)', CURRENT_TIMESTAMP),
  ('KEYWORD', 'click\s*here', 1.5, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'act\s*now', 2.0, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'free\s*money', 3.0, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'you\s*have\s*won', 3.0, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'wire\s*transfer', 2.0, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'nigerian\s*prince', 5.0, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'make\s*money\s*fast', 3.0, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'no\s*obligation', 1.5, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'risk[- ]?free', 1.5, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '100%\s*free', 2.0, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'buy\s*now', 1.0, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'limited\s*time\s*offer', 2.0, 1, '영문 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', 'verify\s*your\s*account', 2.5, 1, '영문 피싱', CURRENT_TIMESTAMP),
  ('KEYWORD', 'suspended\s*your\s*account', 2.5, 1, '영문 피싱', CURRENT_TIMESTAMP),
  ('KEYWORD', 'confirm\s*your\s*(identity|password)', 2.5, 1, '영문 BEC/계정탈취', CURRENT_TIMESTAMP),
  ('KEYWORD', 'unusual\s*sign[- ]?in\s*activity', 2.5, 1, '영문 BEC/계정탈취', CURRENT_TIMESTAMP),
  ('KEYWORD', 'update\s*your\s*(payment|billing)\s*(information|details)', 2.5, 1, '영문 BEC/계정탈취', CURRENT_TIMESTAMP),
  ('KEYWORD', 'gift\s*cards?\s*(now|immediately|asap)', 3.0, 1, '영문 BEC/계정탈취', CURRENT_TIMESTAMP),
  ('KEYWORD', 'urgent\s*(wire|payment|request)', 2.5, 1, '영문 BEC/계정탈취', CURRENT_TIMESTAMP),
  ('KEYWORD', 'invoice\s*attached', 1.0, 1, '영문 BEC/계정탈취', CURRENT_TIMESTAMP),
  ('KEYWORD', 'your\s*(account|mailbox)\s*(has\s*been|will\s*be)\s*(suspended|locked|closed)', 3.0, 1, '영문 BEC/계정탈취', CURRENT_TIMESTAMP),
  ('KEYWORD', '당첨금', 3.0, 1, '한글 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '무료\s*체험', 1.5, 1, '한글 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '대출\s*가능', 2.5, 1, '한글 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '지금\s*바로\s*확인', 1.5, 1, '한글 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '1억원', 2.0, 1, '한글 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '비아그라', 4.0, 1, '한글 고전 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '저?금리\s*대출', 2.5, 1, '한글 대출 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '무직자\s*대출', 3.0, 1, '한글 대출 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '신용\s*불량자?\s*대출', 3.0, 1, '한글 대출 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '당일\s*대출', 2.5, 1, '한글 대출 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '즉시\s*대출', 2.5, 1, '한글 대출 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '총알\s*대출', 3.5, 1, '한글 대출 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '카드\s*깡', 3.5, 1, '한글 대출 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '고수익\s*보장', 3.0, 1, '한글 투자 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '고액\s*알바', 2.5, 1, '한글 구인 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '고소득\s*알바', 2.5, 1, '한글 구인 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '재택\s*알바', 1.5, 1, '한글 구인 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '비트코인\s*무료', 3.0, 1, '한글 투자 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '가상자산\s*(투자|무료)', 2.0, 1, '한글 투자 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '투자\s*권유', 2.0, 1, '한글 투자 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '조건\s*만남', 4.0, 1, '한글 성인 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '출장\s*마사지', 3.0, 1, '한글 성인 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '본인\s*인증', 1.5, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('KEYWORD', '택배\s*(조회|배송)', 1.5, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('KEYWORD', '국세청', 1.5, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('KEYWORD', '등기\s*우편', 1.5, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('KEYWORD', '미납금', 2.0, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('KEYWORD', '체납', 2.0, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('KEYWORD', '법원\s*(출석|통지)', 2.5, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('KEYWORD', '정부\s*지원금', 2.0, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('KEYWORD', '긴급\s*대출', 2.5, 1, '한글 대출 스팸', CURRENT_TIMESTAMP),
  ('KEYWORD', '휴대폰\s*소액\s*결제', 2.0, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('KEYWORD', '결제\s*확인\s*요청', 1.5, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('KEYWORD', '계정\s*(잠금|정지)\s*안내', 2.0, 1, '한글 스미싱', CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'gmail.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'outlook.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'hotmail.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'live.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'msn.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'yahoo.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'yahoo.co.kr', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'naver.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'hanmail.net', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'daum.net', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'nate.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'icloud.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'protonmail.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', '163.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('FREE_MAIL_DOMAIN', 'qq.com', 0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', 'paypal', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', 'apple', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', 'microsoft', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', 'amazon', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', 'netflix', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', 'google', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', 'kakao', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', 'naver', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '국민은행', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '신한은행', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '우리은행', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '하나은행', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '농협', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '카카오뱅크', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '토스', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '국세청', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '우체국', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '택배', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '쿠팡', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('BRAND', '배달의민족', 4.0, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'bit.ly', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'tinyurl.com', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 't.co', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'goo.gl', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'is.gd', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'ow.ly', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'buff.ly', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'rebrand.ly', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'cutt.ly', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'shorturl.at', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'url.kr', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('URL_SHORTENER', 'vo.la', 1.5, 1, NULL, CURRENT_TIMESTAMP),
  ('STRUCTURAL', 'url-raw-ip', 3.0, 1, 'URL 호스트가 raw IP', CURRENT_TIMESTAMP),
  ('STRUCTURAL', 'url-punycode-domain', 3.0, 1, 'URL이 퓨니코드 도메인', CURRENT_TIMESTAMP),
  ('STRUCTURAL', 'missing-date-header', 1.0, 1, 'Date 헤더 누락', CURRENT_TIMESTAMP),
  ('STRUCTURAL', 'missing-message-id', 1.0, 1, 'Message-ID 헤더 누락', CURRENT_TIMESTAMP),
  ('STRUCTURAL', 'envelope-header-recipient-mismatch', 1.5, 1, '봉투-헤더 수신자 불일치', CURRENT_TIMESTAMP),
  ('STRUCTURAL', 'link-heavy-html', 1.5, 1, '링크 위주 HTML 본문', CURRENT_TIMESTAMP),
  ('STRUCTURAL', 'subject-all-caps', 2.0, 1, '제목 전체 대문자', CURRENT_TIMESTAMP),
  ('STRUCTURAL', 'subject-excessive-exclamation', 1.5, 1, '느낌표 3개 이상', CURRENT_TIMESTAMP),
  ('STRUCTURAL', 'empty-body', 1.0, 1, '제목은 있는데 본문이 빔', CURRENT_TIMESTAMP);
